<?php echo $this->doctype(); ?>
<html>
	<head>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
    	<header class="cd-header">
    		<div id="cd-logo"><a href="/index"><img src="/resources/img/logo.svg" alt="Logo"></a></div>
    
    		<nav class="cd-primary-nav">
    			<ul>
    				<li><a href="/index">Home</a></li>
    				<li><a href="/index/shop">Shop</a></li>
    				<li><a href="/index/contacts">Contacts</a></li>
    			</ul>
    		</nav>
    	</header>
		
		<!-- Action Content -->
		<?php echo $this->layout()->content; ?>
		
		<!-- Go to top Button -->
		<a href="#" class="scroll-to-top"></a>
		
		<footer id = "block-footer">
			&#169;Copyright Andrei Profir 2016
		</footer>
	</body>
</html>


