<?php 
    $this->headTitle('Contacts', 'PREPEND');
    $this->headMeta()->appendName('description', 'This is Contacts Page');
    $this->headLink()->appendStylesheet('/css/style-index.css')
        ->appendStylesheet('/css/style.css');
?>

<main class="cd-main-content">
	<div class = "content-contact">
		<div class = "block-list5">
		<div id="list5">
		<h1>HOW TO CONTACT US?</h1>
		<pre>
		
		</pre>
            <ol>
            <li>Address
                <ol>
                    <li>Contrary to popular belief.</li>
                </ol>
            </li>
            <pre>
            
            </pre>
            <li>Work Time
            <ol>
            <li>Monday - Friday: 10:00 - 19:00</li>
            <li>Weekend: Saturday and Sunday</li>
            </ol>
            </li>
            <pre>
            
            </pre>
            <li>Sales Department
            <ol>
            <li><i>tel.:</i> (+373) 22-207-287</li>
            <li><i>mob.:</i> (+373) 79-207-287</li>
            <li><i>fax:</i> (+373) 22-207-286</li>
            <li><i>skype:</i> lorem</li>
			<li><i>e-mail:</i> lorem@gmail.com</li>
            </ol>
            </li>
            </ol>
        </div>
        <div class = "map-img"><h4>WHERE WE ARE</h4><img alt="MAP" src="/resources/img/map.svg"></div>
		</div>
	</div>
</main>
